### ISSUE TITLE
fatal error: lib/axtls/crypto/crypto.h: No such file or directory  #include "lib/axtls/crypto/crypto.h"

### ISSUE THREAD

**Issue by Tkizzy** [adafruit/esp8266-micropython-vagrant#2]
Following the instructions at https://learn.adafruit.com/building-and-running-micropython-on-the-esp8266/build-firmware I'm met with the error

```
fatal error: lib/axtls/crypto/crypto.h: No such file or directory  #include "lib/axtls/crypto/crypto.h"

```

after trying to build the firmware. The toolchain successfully built.

**Comment by jmarron43** [comment]
You're missing these steps:
cd ~/micropython
git submodule update --init
I had the same problem and after that it worked.

The MicroPython source code has already been downloaded to the microython folder during the virtual machine provisioning.  However you need to run a small git command to pull in external dependencies before you can build it.  To install this dependency and then start the compilation execute the following commands inside the virtual machine:

JM

**Comment by tdicola** [comment]
Oh thanks for catching this and apologies it took a little while to be reviewed.  Yeah I noticed this too recently and updated the guide to call out the git submodule init.  Thanks!

**Comment by gwaland** [comment]
This is apparently still missing in the readme.md.
