### ISSUE TITLE
micropython 8266 webrepl

### ISSUE THREAD

**Issue by jhlucky** [adafruit/esp8266-micropython-vagrant#6]
when I use micropython-8266 with 'import webrepl_setup'
The correct results :would you like to (E)nable or (D)isenable it running on boot?
    choose 'E'
    To enable WEBREPL.you must...
But in myself:
    choose 'E'
    No further action required.
and exit .
How to solve this?thanx

**Comment by kattni** [comment]
This library is no longer supported. We are only supporting CircuitPython. Please consider this guide on building CircuitPython: https://learn.adafruit.com/building-circuitpython
