### ISSUE TITLE
cp: cannot stat ‘config/upyconfig’: No such file or directory

### ISSUE THREAD

**Issue by bmsleight** [adafruit/esp8266-micropython-vagrant#7]
After:-

```
cd ~/micropython/esp8266
make
```

Had an error:-
`cp: cannot stat ‘config/upyconfig’: No such file or directory`

Had to re-clone and get submodules
```
sudo rm -r ./micropython
git clone http://github.com/micropython/micropython.git
cd micropython
git submodule update --init
cd esp8266
make
```

referenced https://github.com/micropython/micropython/issues/2952

**Comment by kattni** [comment]
This library is no longer supported. We are only supporting CircuitPython. Please consider this guide on building CircuitPython: https://learn.adafruit.com/building-circuitpython
