### ISSUE TITLE
Vagrantfile: clones micropython vs circuitpython

### ISSUE THREAD

**Issue by sommersoft** [adafruit/esp8266-micropython-vagrant#8]
Vagrantfile: L35 is cloning micropython, not circuitpython. Since adafruit is now maintaining the esp8266 in circuitpython, this should probably be updated.
  
```
git clone https://github.com/micropython/micropython.git
```

**Comment by kattni** [comment]
This library is no longer supported. We are only supporting CircuitPython. Please consider this guide on building CircuitPython: https://learn.adafruit.com/building-circuitpython
